- name: Install Node
  uses: actions/setup-node@v4
- name: Check node version
  run: npm --version
- name: Build Inspectify frontend
  env:
    PUBLIC_API_BASE: ""
    PUBLIC_CHECKO: ""
  run: |
    cd ./apps/inspectify/
    npm install
    npm run build
