[package]
name = "driver"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ce-core.workspace = true
ce-shell.workspace = true
color-eyre.workspace = true
dunce.workspace = true
futures-util.workspace = true
glob = "0.3.1"
itertools.workspace = true
notify = "8.0.0"
notify-debouncer-mini = { version = "0.6.0", default-features = false }
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true
stdx.workspace = true
tapi.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
