[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = true
# Path that installers should place binaries in
install-path = "CARGO_HOME"
github-build-setup = "../build-setup.yml"

[dist.github-custom-runners]
runner = "ubuntu-22.04"

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-22.04"

# TODO: this didn't work on the version of ubuntu dist uses currently
# [dist.dependencies.homebrew]
# just = "*"
# [dist.dependencies.apt]
# nodejs = "*"
# just = "*"
# [dist.dependencies.chocolatey]
# nodejs = "*"
# just = "*"
