FROM rustlang/rust:nightly-slim

ENV CARGO_TARGET_DIR=/.cargo-target

COPY rust-toolchain.toml /root/
WORKDIR /root/

RUN cargo install --quiet cargo-binstall
RUN cargo binstall --no-confirm --quiet \
    just \
    typeshare-cli

RUN mkdir -p /usr/local/n/versions && \
    curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | bash -s latest

WORKDIR /root/code
