FROM rustlang/rust:nightly-slim

ENV CARGO_TARGET_DIR=/.cargo-target

COPY rust-toolchain.toml /root/
WORKDIR /root/

RUN cargo install --quiet cargo-binstall
RUN cargo binstall --no-confirm --quiet \
    just \
    typeshare-cli \
    cross

RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

RUN mkdir -p /usr/local/n/versions && \
    curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | bash -s latest

ENV CROSS_CONTAINER_IN_CONTAINER=true
RUN apt-get update && apt-get install -y curl && curl -fsSL https://get.docker.com | sh

WORKDIR /root/code
