CHECKO := "cargo run --release -p checko --"

run-tests:
    {{CHECKO}} run-tests -p programs.toml -g groups.toml -s submissions/

push-results:
    {{CHECKO}} push-results-to-repos -g groups.toml -s submissions/

push-results-execute:
    {{CHECKO}} push-results-to-repos -g groups.toml -s submissions/ --execute

generate-competition:
    {{CHECKO}} generate-competition -g groups.toml -s submissions/ -o competition-results.md
