/*
 Generated by typeshare 1.0.0
*/

export interface Sample {
	input_json: string;
	input_md: string;
	output_md: string;
}

export interface Env {
	name: string;
	input_json: string;
	input_markdown: string;
	output_markdown: string;
}

export interface Generation {
	program: string;
	dot: string;
	envs: Env[];
}

