default:
    # rm -rf example
    cargo run -- test example-config.toml --base example

generate-self:
    RUST_LOG=debug cargo run -- generate-report .. -g 2 -o result.md

generate-vagt:
    RUST_LOG=debug cargo run -- generate-report --no-hidden ../gcmd/ -g 2 -o result.md

docker-shell:
    docker build . -t vl-infra
    docker run -it --rm -v $(realpath ../):/root/code vl-infra bash
