/*
 Generated by typeshare 1.2.0
*/

export type Markdown = string;

export interface CompilationStatus {
	compiled_at: number;
	state: CompilerState;
}

export interface Input {
	analysis: Analysis;
	json: string;
	markdown: Markdown;
}

export interface Output {
	analysis: Analysis;
	json: string;
	markdown: Markdown;
}

export interface GraphRequest {
	src: string;
	deterministic: boolean;
}

export interface AnalysisRequest {
	analysis: Analysis;
	src: string;
	input: string;
}

export interface AnalysisResponse {
	stdout: string;
	stderr: string;
	parsed_markdown?: Markdown;
	took: string;
	validation_result?: ValidationResult;
}

export enum Analysis {
	Graph = "Graph",
	Parse = "Parse",
	Interpreter = "Interpreter",
	ProgramVerification = "ProgramVerification",
	Sign = "Sign",
	Security = "Security",
}

export type CompilerState = 
	| { type: "Compiling", content?: undefined }
	| { type: "Compiled", content?: undefined }
	| { type: "CompileError", content: {
	stdout: string;
	stderr: string;
}};

export type ValidationResult = 
	| { type: "CorrectTerminated", content?: undefined }
	| { type: "CorrectNonTerminated", content: {
	iterations: number;
}}
	| { type: "Mismatch", content: {
	reason: string;
}}
	| { type: "InvalidInput", content: {
	input: string;
	error: string;
}}
	| { type: "InvalidOutput", content: {
	output: string;
	expected_output_format?: string;
	error: string;
}}
	| { type: "TimeOut", content?: undefined };

export type GraphResponse = 
	| { type: "Graph", content: {
	dot: string;
}}
	| { type: "Error", content: {
	error: string;
}};

